config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  get 'config/beep' => 'beep#show'
  put 'config/beep/:beep_value' => 'beep#update', as: :beep_update

  get 'config/purge' => 'purge#show'
  put 'config/purge/:days_to_purge' => 'purge#update', as: :purge_update

  get 'config/update' => 'config#update_config'
  get 'files' => 'files#index'
  get 'files/:filename' => 'files#get', as: :file_download
  delete 'files/delete/:filename' => 'files#delete', as: :file_delete
  get 'config' => 'config#index'

end

app/models/beep_value.rb
class Beep_value
# Include nicht vergessen

#function for update beep_value
def self.update(val)
  # in file herein schreiben
  # val ist der neue wert
  File.open('/home/pi/motionui/security-camera/beep.txt', 'w') { |file| file.write(val)}
end

#show beep time value
def self.show
  # aus File heraus lesen
  file = File.open('/home/pi/motionui/security-camera/beep.txt')
  time = file.read

end


end

app/models/config.rb
class Config
  require 'yaml'
  @@settings

  #get allowed config values
  def self.get_config_objects
    values = self.get_config
    config_obj = []

    @@settings.each do |setting|
      line = Config_line.new
      line.key = setting[0]
      line.current_value = values[setting[0]]
      line.allowed_values = setting[1]['allowed']
      config_obj << line
    end
    config_obj
  end

  #get alloew settings from yml list
  def self.get_config
    values = {}
    @@settings ||= YAML.load_file(Rails.root.join('config', 'allowed_settings.yml'))
    remote_config ||= HTTParty.get($motion_api_base_path+"0/config/list")

    remote_config.lines.each do |line|
      itemvalues = line.split(' = ')
      values[itemvalues[0]] = itemvalues[1][0..-2]
    end
    values
  end
end

app/models/config_line.rb
class Config_line
  attr_accessor :key, :current_value, :allowed_values
end

app/models/purge_time.rb
class Purge_time
# Include nicht vergessen

#update purge time
def self.update(val)
  # in file herein schreiben
  # val ist der neue wert
  File.open('/home/pi/motionui/security-camera/ini.txt', 'w') { |file| file.write(val)}


end

#show purge value
def self.show
  # aus File heraus lesen
  file = File.open('/home/pi/motionui/security-camera/ini.txt')
  time = file.read

end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session


#Read ip from ip.txt
  file = File.open('/home/pi/motionui/security-camera/ip.txt')
  ip = file.read

#set variables for motion_api_base_path and motion_live_stream_path
  $motion_api_base_path = "http://"+ip.strip+":8080/"
  $motion_live_stream_path = "http://"+ip.strip+":8081"

end

app/controllers/beep_controller.rb
class BeepController < ApplicationController
  before_action :beep_params, only:[:update]
  attr_accessor :beep

#function to update beep_value
  def update
    Beep_value.update(beep_params)
    redirect_to :back
  end

#function to show beep_value 
  def show
    $beep = Beep_value.show
  end

  private
    def beep_params
      params.require(:beep_value)
    end
end

app/controllers/config_controller.rb
class ConfigController < ApplicationController

  #lists all config options (logic in model Config)
  def index
    @settings = Config.get_config_objects
  end


  # this supports a key and a value update function
  #update config value
  def update_config

    url = $motion_api_base_path+ '0/config/set?' + params[:key] + '=' + params[:value]
    result = HTTParty.get(url)
    redirect_to :back
  end

end

app/controllers/files_controller.rb
class FilesController < ApplicationController

  #list all files
  def index
    @files = []
    Dir.foreach(get_video_path) {|x|
      @files << x if x.last(4) == '.mp4'
    }
    respond_to do |format|
      format.json { render json: @files }
      format.html
    end
  end

  #get a file (download)
  def get
    send_file get_video_path + '/' + params[:filename] + '.mp4'
  end

  #delete a file
  def delete
    #this uses HTTP DELETE, so be sure to use this in your links
    File.delete get_video_path + '/' + params[:filename] + '.mp4'
    redirect_to :back
  end

  #get video path
  private
  def get_video_path
    Rails.application.config.video_path
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  #show status from motion and get livestream
  def index
    @status = HTTParty.get($motion_api_base_path)
    @live_stream_url = $motion_live_stream_path
    respond_to do |format|
      format.html
      format.json { render json: @status }
    end
  end


end

app/controllers/purge_controller.rb
class PurgeController < ApplicationController

before_action :purge_params, only:[:update]

#update value purge (logic in model Purge_time)
def update
  Purge_time.update(purge_params)
  redirect_to :back
end

#show purge time (logic in model Purge_time)
def show
  $purge_time = Purge_time.show
end

private
  def purge_params
    params.require(:days_to_purge)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beep_helper.rb
module BeepHelper
end

app/helpers/purge_helper.rb
module PurgeHelper
end

app/views/beep/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <table class="table">
      <tr>
        <th>
          Key
        </th>
        <th>
          Current Value
        </th>
        <th>
          Set
        </th>
        <tr>
          <td>Purge Days</td>
          <td><h1>Listing Books</h1>

<table>
  <tr>
    <th><%= @beep %></th>
    <th>Summary</th>

  </tr>

  <tr>
          <td class="buttons">
            <%=button_to("3", purge_update_path(3), method: "put", class: "btn btn-default") %>
            <%=button_to("5", purge_update_path(5), method: "put", class: "btn btn-default") %>
            <%=button_to("8", purge_update_path(8), method: "put", class: "btn btn-default") %>
          </td>
  </tr>
</table>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/config/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <table class="table">
      <tr>
        <th>
          Key
        </th>
        <th>
          Current Value
        </th>
        <th>
          Set
        </th>
        <tr>
          <td>purge_time</td>
          <td><%= $purge_time %></td>
          <td class="buttons">
            <%=button_to("3", purge_update_path(3), method: "put", class: "btn btn-default") %>
            <%=button_to("5", purge_update_path(5), method: "put", class: "btn btn-default") %>
            <%=button_to("8", purge_update_path(8), method: "put", class: "btn btn-default") %>
          </td>
        </tr>
        <tr>
          <td>beep_value</td>
          <td><%= $beep %></td>
          <td class="buttons">
            <%=button_to("ON", beep_update_path("on"), method: "put", class: "btn btn-default") %>
            <%=button_to("OFF", beep_update_path("off"), method: "put", class: "btn btn-default") %>
          </td>
        </tr>
        <% @settings.each do |setting| %>
        <tr>
          <td><%=setting.key %></td>
          <td><%=setting.current_value %></td>
          <td class="buttons">
            <% setting.allowed_values.each do |val| %>
              <% if val.to_s == setting.current_value %>
                <a class="btn btn-default disabled"><%=val %></a>
              <% else %>
                <a href="<%=config_update_path(:key => setting.key, :value => val ) %>" class="btn btn-default"><%=val %></a>
              <% end %>
            <% end %>
          </td>
        </tr>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/files/index.html.erb
  <div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <table class="table">
      <tr>
        <th>
          Name
        </th>
        <th>
        </th>
        <th>
        </th>
        <th>
        </th>
      </tr>
      <%i = 1 %>
      <% @files.each do |file| %>
      <tr>
      <td>
        <%=file %>
      </td>
      <td>
      <%=button_to("Download", file_download_path(file), method: "get", class: "btn btn-default") %>
      </td>
        <td>
          <%=button_to("Delete", file_delete_path(file), method: "delete", class: "btn btn-default") %>
        </td>
        <td>
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal_<%=i %>">
            <%=file%>
          </button>
          <div class="modal fade" id="modal_<%=i%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModal"><%=file%></h4>
                </div>
                <div class="modal-body">
                  <%= video_tag(file_download_path(file), controls: true) %>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
      <%i = i + 1 %>
      <% end %>
    </table>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/index/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-3">
    <span class="label label-info">
      <%=@status %>
    </span>
  </div>
    <div class="col-md-5">
    <div class="livestream">
      <% if @live_stream_url %>
        <img class="img-responsive" src="<%=@live_stream_url %>"/>
      <% end %>
    </div>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Motionui</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <div class="col-md-12">
          <div class="logo">
            <a href="/"><%= image_tag ("ueberwachungsloesung_logo.jpg")%></a>
          </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-inverse" role="banner">
          <div class="container">
            <div class="navbar-header">
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">Home</a>
            </div>
            <nav class="collapse navbar-collapse" role="navigation">
              <ul class="nav navbar-nav">
                <li>
                  <a href="/files">Files</a>
                </li>
                <li>
                  <a href="/config">Config</a>
                </li>
                <li>
                  <a href="#sec">API Docu</a>
                </li>
              </ul>
            </nav>
          </div>
        </nav>
      </div>
    </div>
  </body>
  <%=yield %>

</html>

app/views/purge/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <table class="table">
      <tr>
        <th>
          Key
        </th>
        <th>
          Current Value
        </th>
        <th>
          Set
        </th>
        <tr>
          <td>Purge Days</td>
          <td><h1>Listing Books</h1>

<table>
  <tr>
    <th><%= @purge_time %></th>
    <th>Summary</th>

  </tr>

  <tr>
          <td class="buttons">
            <%=button_to("3", purge_update_path(3), method: "put", class: "btn btn-default") %>
            <%=button_to("5", purge_update_path(5), method: "put", class: "btn btn-default") %>
            <%=button_to("8", purge_update_path(8), method: "put", class: "btn btn-default") %>
          </td>
  </tr>
</table>
  </div>
  <div class="col-md-2"></div>
</div>